// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXRjDb7ZfY3vJJIJjvScuu3UuiN85AHSQ',
    appId: '1:330331130378:web:22d467949f1202800fedf3',
    messagingSenderId: '330331130378',
    projectId: 'jhj-flutter-first',
    authDomain: 'jhj-flutter-first.firebaseapp.com',
    storageBucket: 'jhj-flutter-first.appspot.com',
    measurementId: 'G-S0S4SNBFXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1fmUg5dJhmjwCyuPxMHr85dTmWgB8loQ',
    appId: '1:330331130378:android:763030d4f59e33810fedf3',
    messagingSenderId: '330331130378',
    projectId: 'jhj-flutter-first',
    storageBucket: 'jhj-flutter-first.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSGwiwn5PMpQUJQUnP75ID3Jj5LFiXdNg',
    appId: '1:330331130378:ios:3681b7d15b9be2920fedf3',
    messagingSenderId: '330331130378',
    projectId: 'jhj-flutter-first',
    storageBucket: 'jhj-flutter-first.appspot.com',
    iosClientId: '330331130378-jvkei5l84qqrod9sqo1glenfglmptjfq.apps.googleusercontent.com',
    iosBundleId: 'org.study.jhj',
  );
}
